### ISSUE TITLE
PPO采用zero 3 stage后产生time out error

### ISSUE THREAD

**Issue by victorShawFan** [OpenRLHF/OpenRLHF#293]
<img width="747" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/366314a2-2a37-4a35-bc30-e96411623e70">
<img width="743" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/84c7a1d5-7572-4c4d-9445-406a9ce2136c">
<img width="739" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/2e0205dc-683d-465a-9447-3b7980958cb7">
脚本修改如下，ckpt换为Qwen：
<img width="593" alt="image" src="https://github.com/OpenLLMAI/OpenRLHF/assets/40328132/ccad06db-4f77-40d1-9bc2-7ae79d627f75">

**Comment by hijkzzz** [comment]
有可能是deepspeed的问题 可以尝试降低一下版本号

**Comment by yinzhijian** [comment]
@victorShawFan 请教下这个问题解决了吗，怎么解决的？

**Comment by Hzlvv** [comment]
我也遇到了一样的问题，似乎是卡在了NaiveExperienceMaker里make_experience函数的action_log_probs = self.actor(sequences, num_actions, attention_mask) 这一句或者base_action_log_probs = self.initial_model(sequences, num_actions, attention_mask)

stage 2的话就没有任何问题，stage3就有问题。 求大佬帮忙看看 @hijkzzz 

deepspeed是0.13.5

**Comment by 18140663659** [comment]
> generate_max_len

遇到一样的问题，改成2之后正常

**Comment by tzuhanlin0316** [comment]
> 好像在actor中， model.generate() 这句加上synced_gpus=True就可以了--
This may solve the issue when using zero-3. @hijkzzz can you guys check about whether the `synced_gpus` is set when `zero-3` is enabled? According to the official doc, it seems that it should be enabled automatically when using `zero-3`. But I need to manually set it so that it will not get stuck during training.

Official doc: https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationMixin.generate

**Comment by Viper403** [comment]
I have met the same "Timeout" problem when using zero-stage-3. After adding `synced_gpus=True`, there comes a new but strange Bug.

[rank5]: Traceback (most recent call last):
[rank5]:   File "/xxx/OpenRLHF/openrlhf/cli/train_grpo.py", line 331, in <module>
[rank5]:     train(args)
[rank5]:   File "/xxx/OpenRLHF/openrlhf/cli/train_grpo.py", line 207, in train
[rank5]:     trainer.fit(args, prompts_dataloader, pretrain_dataloader, consumed_samples, num_update_steps_per_episodes)
[rank5]:   File "/xxx/OpenRLHF/openrlhf/trainer/grpo_trainer.py", line 170, in fit
[rank5]:     experience = self.experience_maker.make_experience(rand_prompts, **self.generate_kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank5]:     return func(*args, **kwargs)
[rank5]:   File "/xxx/OpenRLHF/openrlhf/trainer/ppo_utils/experience_maker.py", line 541, in make_experience
[rank5]:     sequences, attention_mask, action_mask = self.actor.generate(**inputs, **generate_kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank5]:     return func(*args, **kwargs)
[rank5]:   File "/xxx/OpenRLHF/openrlhf/models/actor.py", line 150, in generate
[rank5]:     sequences = self.model.generate(**generate_args)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank5]:     return func(*args, **kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/transformers/generation/utils.py", line 1989, in generate
[rank5]:     result = self._sample(
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2932, in _sample
[rank5]:     outputs = self(**model_inputs, return_dict=True)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1141, in forward
[rank5]:     outputs = self.model(
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 944, in forward
[rank5]:     layer_outputs = decoder_layer(
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 677, in forward
[rank5]:     hidden_states, self_attn_weights, present_key_value = self.self_attn(
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1582, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:   File "/usr/python3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 372, in forward
[rank5]:     attn_weights = attn_weights + causal_mask
[rank5]: RuntimeError: The size of tensor a (1119) must match the size of tensor b (1118) at non-singleton dimension 3

This really confuses me, since zero-stage-2 works well.  I use the script in the `examples` folder. I tried both deepspeed==0.14.4 and deepspeed==0.13.5.
